
package schemas.dynamics.microsoft.page.item;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Item_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemPort {


    /**
     * 
     * @param no
     * @return
     *     returns schemas.dynamics.microsoft.page.item.Item
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/item:Read")
    @WebResult(name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.ReadResult")
    public Item read(
        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        String no);

    /**
     * 
     * @param recId
     * @return
     *     returns schemas.dynamics.microsoft.page.item.Item
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/item:ReadByRecId")
    @WebResult(name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.ReadByRecIdResult")
    public Item readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        String recId);

    /**
     * 
     * @param setSize
     * @param bookmarkKey
     * @param filter
     * @return
     *     returns schemas.dynamics.microsoft.page.item.ItemList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/item:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.ReadMultipleResult")
    public ItemList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        List<ItemFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/item:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/item:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        String key);

    /**
     * 
     * @param item
     */
    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/item:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.CreateResult")
    public void create(
        @WebParam(name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", mode = WebParam.Mode.INOUT)
        Holder<Item> item);

    /**
     * 
     * @param itemList
     */
    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/item:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.CreateMultipleResult")
    public void createMultiple(
        @WebParam(name = "Item_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", mode = WebParam.Mode.INOUT)
        Holder<ItemList> itemList);

    /**
     * 
     * @param item
     */
    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/item:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.UpdateResult")
    public void update(
        @WebParam(name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", mode = WebParam.Mode.INOUT)
        Holder<Item> item);

    /**
     * 
     * @param itemList
     */
    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/item:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.UpdateMultipleResult")
    public void updateMultiple(
        @WebParam(name = "Item_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", mode = WebParam.Mode.INOUT)
        Holder<ItemList> itemList);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/item:Delete")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "schemas.dynamics.microsoft.page.item.DeleteResult")
    public boolean delete(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        String key);

}
